name: "Actions to perform on a merge to master"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]

jobs:
  test_code:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install the dependencies
        run: yarn install

      # Runs a single command using the runners shell
      - name: Run the unit tests
        run: yarn test:ci
